### ISSUE TITLE
wrong license

### ISSUE THREAD

**Issue by stiv-yakovenko** [KoynovStas/wsdd#8]
Build process involves using gsoap-2.8, which generates GPL-licensed files. So resulting license, unfortunately should be GPL...

**Comment by genivia-inc** [comment]
When GPL is combined with BSD, the GPL is still applicable to the overall software:

Your modified version of the BSD-licensed code depends on the GPLv2-licensed code. In that case, the FSF would say that your code can no longer be distributed solely under the BSD license; it must carry the GPL as well, because of the dependance on GPL-licensed material. See https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works

Therefore, this project must be licensed as GPLv2.

**Comment by KoynovStas** [comment]
Yes, I admit that I was wrong when I chose the BSD license of the entire project. It's clearly indicated in the GPLv2 license,
namely [paragraph 2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html):

> These requirements apply to the modified work as a whole. If identifiable sections of that work are not derived from the Program, and can be reasonably considered independent and separate works in themselves, then this License, and its terms, do not apply to those sections when you distribute them as separate works. But when you distribute the same sections as part of a whole which is a work based on the Program, the distribution of the whole must be on the terms of this License, whose permissions for other licensees extend to the entire whole, and thus to each and every part regardless of who wrote it.

 BSD-3-Clause **is compatible** with the GPLv2 license see: [The Free-Libre / Open Source Software (FLOSS) License Slide](https://dwheeler.com/essays/floss-license-slide.html)

I asked a specialist Dr. Susanne Cappendijk, PhD, MBA
from the company Genivia Inc. 
Question:
> But I do not understand what I have to do with the comments about the BSD license in the files. Should I remove it?
> Or should I clarify in file (README.md) that these files can be used outside the project under the BSD license, and in this project under the GPL license. because the GPL absorbed a weaker BSD license.
> How is this problem solved?

She didn't answer, but I've found the answer [here!](https://opensource.stackexchange.com/questions/4010/using-freebsd-licensed-code-in-a-gpl3-project)

So I'm gona change the license of the entire project to GPLv2 and leave the files with the BSD license unchanged. These outside the project files (separately from the project) can be used under the license of the BSD. Whereas the entire project is still licensed under GPLv2.

If this is suitable for everyone, I'll do this work as soon as I have free time.

**Comment by genivia-inc** [comment]
> BSD-3-Clause **is compatible** with the GPLv2 license see: [The Free-Libre / Open Source Software (FLOSS) License Slide](https://dwheeler.com/essays/floss-license-slide.html)

This is true only in one direction. It is possible to include BSD-3-Clause licensed code (a weak license) in GPLv2 code (a stronger license), but not the other way. Simply put, you can't weaken GPLv2 without infringing on IP rights.

It must be clear to users of your project that your project can only be used under a GPLv2 license, not BSD. Otherwise there will be IP rights issues. The best way to do this is to make the project GPLv2 licensed by replacing LICENSE.

> So I'm gona change the license of the entire project to GPLv2 and leave the files with the BSD license unchanged. 

Indeed, that must be done. Change LICENSE please.
